### ISSUE TITLE
Do not account newline symbol (i.e., '\n') to the number of characters in a line

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/checkpatch#18]
Seems like the newline symbol is sometimes (in an inconsistent matter) taken into account when counting the number of characters in a line: I feel this is redundant and irritating.

**Comment by locker** [comment]
There's a different line length limit for Git commit messages - 75 characters. The reason for this limit is that `git log` indents commit messages by 4 characters so exceeding 75 characters would result in too long (>80 characters) lines printed in the terminal. I think we should keep the check.

**Comment by locker** [comment]
This happens, because the string contains unicode symbols. By default, Perl counts the number of octets in the string so a unicode symbol counts as a few characters.

**Comment by CuriousGeorgiy** [comment]
Reproducer for FP `LONG_LINE_COMMENT` error:
[0001-memtx-rework-transaction-rollback.patch.zip](https://github.com/tarantool/checkpatch/files/9038382/0001-memtx-rework-transaction-rollback.patch.zip)

**Comment by locker** [comment]
Although I wouldn't use non-ASCII characters in comments to C code...

**Comment by CuriousGeorgiy** [comment]
@locker 

I use them em dash as a punctuation symbol and for drawing contiguous lines in text graphics. 

Perhaps, you could forbid this in checkpatch.

**Comment by Totktonada** [comment]
My opinion about using non-ASCII symbols in different contexts is summarized below.

> There are technical texts, which aim direct reading (without any pre-rendering) as a primary or a second goal (say, markdown supports rendering, but easy to read directly). The most obvious example is a comment in code. All or most of text that are tightly connected to code are also of this kind: they are usually written as plain text, asciidoc, markdown. Here non-ASCII symbols are generally discouraged. Here we expect a hyphen (or two hyphens), where in book we would see a dash.
>
> There are texts, which primarily aim some rendering tool, which will prettify it, inline hyperlinks and convert to a format of a reader tools (generate HTML, PDF and so on). Those are texts for modern websites for example. Here we use Unicode en/em dash symbols or a special syntax to represent them using ASCII.

(Originally written [here](https://github.com/tarantool/tarantool/pull/6846#discussion_r809512335).)
