### ISSUE TITLE
checkpatch stops on ```

### ISSUE THREAD

**Issue by tsafin** [tarantool/checkpatch#19]
Apparenly triple qoutes (opening markdown code block)  stops `checkpatch` regardless whether we have anything after block closed ot not. Thus we could not put `NO_CHANGELOG`/`NO_DOC` lines below code block, only above.

https://github.com/tarantool/tarantool/pull/7195/commits/ad0f0cec12273f5eecb9fe8173279a752923c85a

**Comment by Totktonada** [comment]
Is not it duplicate of #14? Whether your problem actually is in backticks, not dashes?

**Comment by tsafin** [comment]
> Whether your problem actually is in backticks, not dashes?

Yeah, smells like a duplicate, but complaining about different things. Let me check.

**Comment by tsafin** [comment]
@Totktonada yes, the problem was in triple dash, not triple backticks. Thanks for the advice! (Once I've changed it to double dash in https://github.com/tarantool/tarantool/pull/7195/commits/2be6485ff20baf4dcd2c8e88370b55247ca7a7ba - `checkpatch` has stopped their complains)
