### ISSUE TITLE
False positive COMPLEX_MACRO

### ISSUE THREAD

**Issue by Lord-KA** [tarantool/checkpatch#24]
Example:
https://github.com/tarantool/tarantool/runs/7075031544?check_suite_focus=true
Usage example:
https://github.com/tarantool/tarantool/commit/4cd891c64e7c27cdc9f11426c7d2a7f4a81f43ad#diff-0658926aabc4deaab91d4b0ac945c852250418bfc3fcf0c2cdb3326be0501681
```
#define ALL_OPTIONS_	\
	OPTION(LUA_TBOOLEAN, encode_sparse_convert, 1)   	\
	OPTION(LUA_TNUMBER,  encode_sparse_ratio, 2)	  	\
	OPTION(LUA_TNUMBER,  encode_sparse_safe, 10)		\
	OPTION(LUA_TNUMBER,  encode_max_depth, 128)		\
	OPTION(LUA_TBOOLEAN, encode_deep_as_nil, 0)		\
	OPTION(LUA_TBOOLEAN, encode_invalid_numbers, 1)		\
	OPTION(LUA_TNUMBER,  encode_number_precision, 14)	\
	OPTION(LUA_TBOOLEAN, encode_load_metatables, 1)		\
	OPTION(LUA_TBOOLEAN, encode_use_tostring, 0)		\
	OPTION(LUA_TBOOLEAN, encode_invalid_as_nil, 0)		\
	OPTION(LUA_TBOOLEAN, encode_error_as_ext, 1)		\
	OPTION(LUA_TBOOLEAN, encode_esc_slash, 0)		\
	OPTION(LUA_TBOOLEAN, decode_invalid_numbers, 1)		\
	OPTION(LUA_TBOOLEAN, decode_save_metatables, 1)		\
	OPTION(LUA_TNUMBER,  decode_max_depth, 128)
```
This type of macro can not be enclosed in parentheses.

**Comment by locker** [comment]
I think we should avoid using macros that expand in unbalanced C/C++ constructs. See the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Preprocessor_Macros) for why.
