### ISSUE TITLE
Checkpatch doesn't allow to update a diff-based test

### ISSUE THREAD

**Issue by Gerold103** [tarantool/checkpatch#37]
I needed to update an old diff-based test after some functional changes, but checkpatch marks such commit as an error. I wouldn't want to convert each touched .test.lua file to luatest.
```
ERROR: Please avoid tests with .result files
```

**Comment by Totktonada** [comment]
Duplicate of #35.

**Comment by Gerold103** [comment]
Indeed, a duplicate.
