### ISSUE TITLE
Extend comment line length limit to 80

### ISSUE THREAD

**Issue by Gerold103** [tarantool/checkpatch#5]
The linter says *ERROR: Possible unwrapped commit description (prefer a maximum 75 chars per line)* for too long comments, but I think our SOP / dev-guideline allows up to 80 (I don't know where it is written exactly though).

**Comment by locker** [comment]
I can remove the check, but the [reasoning](https://github.com/torvalds/linux/commit/2a076f40d8c9be95bee7bcf18436655e1140447f) behind the 75 characters line length for git commit messages makes sense:

> Suggest line wrapping at 75 columns so the default git commit log indentation of 4 plus the commit message text still fits on an 80 column screen.

It's usually recommended to wrap commit message at 72 characters. For example, vim does that by default.

**Comment by Gerold103** [comment]
Ah, wait. It is my fault - I thought it was about a comment in the code. I didn't look at the error message carefully enough. Sorry for the confusion.
