### ISSUE TITLE
Disallow "... = ... or ..." in lua

### ISSUE THREAD

**Issue by grafin** [tarantool/checkpatch#52]
Because of `box.NULL` being equal to `nill` but not being equal to `false` usual lua constructions like `opts = opts or {}` can lead to problems like https://github.com/tarantool/tdg2/issues/1546. After we fix [all current similar problems](https://github.com/tarantool/tdg2/issues/1825) it would be great, if we could automatically prevent new ones.

**Comment by locker** [comment]
I think this had better be checked by [luacheck](https://github.com/tarantool/luacheck).

**Comment by grafin** [comment]
Moved to https://github.com/tarantool/luacheck/issues/17
